Accessibility options for indoor directions
felixlapierre/campus-guide pull request #214
Opened 2020-04-19 07:26 UTC by gdzooks

Things in this PR:
* Update to the UI to add a menu that allows you to open a popup with selectable accessibility options!
* The feature's logic!

Things not in this PR:
* Tests
* Refactoring that might have been template method but my brain refuses to read or write so here we are

Could not test the feature on my phone because master doesn't have indoor directions displaying on the correct floor for directions so... idk........

**NOTE**
If this doesn't build on your computer, I recommend you _clean_ the project and then build again. If you get a "Content is not allowed in prolog" error like @sharon-ho .... I cannot help you I do not understand it...

2020-04-19 17:37 UTC, sharon-ho requested changes
No further refactoring I can personally recommend. Just a couple changes to use constants for strings as suggested below.

2020-04-19 17:37 UTC, sharon-ho commented on app/src/main/java/com/example/campusguide/Accessibility.kt
> +        forbiddenRooms.add("elevators")
You can make strings `"elevators"`, `"stairs"` and `"elevators"` as string variables to pass.

2020-04-19 17:37 UTC, sharon-ho commented on app/src/main/java/com/example/campusguide/directions/indoor/SelectAccessibilityOptionsDialogFragment.kt
> +            .setTitle("Select one or more options")
You can make the title string as a constant in `Constants`.

2020-04-19 17:37 UTC, sharon-ho commented on app/src/main/java/com/example/campusguide/directions/indoor/SelectAccessibilityOptionsDialogFragment.kt
> +        }.setNegativeButton("Cancel", null)
Use the string constants `CONFIRM_CHOICE` and `CANCEL_CHOICE` for the button setters.

2020-04-19 17:37 UTC, sharon-ho commented on app/src/main/res/layout/accessibility_select_in_directions.xml
> +        android:text="Can't Use Escalators"/>
Extract these hard-coded strings into `@string` resources xml (i.e. can't use escalators, elevators or stairs).

2020-04-19 17:37 UTC, sharon-ho commented on app/src/main/res/menu/accessibility_menu.xml
> +        android:title="Change Indoor Accessibility"/>
Extract these hard-coded strings into @string resources xml (i.e. can't use escalators, elevators or stairs).

2020-04-19 18:17 UTC, felixlapierre commented
Currently investigating something that's preventing this from working properly

2020-04-20 02:16 UTC, sharon-ho approved these changes
Approving changes made!

2020-04-20 02:24 UTC, merged