28 location search
felixlapierre/campus-guide pull request #51
Opened 2020-02-10 03:18 UTC by MikeBrichko

Adding location search feature

2020-02-10 03:35 UTC, felixlapierre commented
Pls fix merge conflicts before review 😃

2020-02-10 03:41 UTC, MikeBrichko commented
Oops! I forgot to push my merge conflict fixes before making the pull request

2020-02-10 18:21 UTC, FGRCL commented
91 files is huge are they all necessary?

2020-02-10 18:23 UTC, FGRCL requested changes

2020-02-10 18:23 UTC, FGRCL commented on app/.idea/codeStyles/Project.xml
> +<component name="ProjectCodeStyleConfiguration">
I think all the .idea/ files should be added to the gitignore

2020-02-25 21:11 UTC, felixlapierre requested changes

2020-02-25 21:11 UTC, felixlapierre commented on app/build.gradle
> +    testImplementation 'junit:junit:4.12'
Duplicate of line 41 in this file

2020-02-25 21:11 UTC, felixlapierre commented on .idea/codeStyles/Project.xml
> -    <AndroidXmlCodeStyleSettings>
Is this necessary?

2020-02-25 21:11 UTC, felixlapierre commented on .idea/gradle.xml
> +  <component name="GradleMigrationSettings" migrationVersion="1" />
Are these changes necessary?

2020-02-25 21:11 UTC, felixlapierre commented on app/build.gradle
> -    implementation 'androidx.core:core-ktx:1.0.2'
Are we sure we don't need this?

2020-02-25 21:11 UTC, felixlapierre commented on app/local.properties
> +sdk.dir=C\:\\Users\\wmike\\AppData\\Local\\Android\\sdk
Definitely shouldn't be here

2020-02-25 21:11 UTC, felixlapierre commented on app/src/main/AndroidManifest.xml
> +        <uses-library android:name="org.apache.http.legacy" android:required="false"/>
Is this necessary?

2020-02-25 21:11 UTC, felixlapierre commented on app/src/main/java/com/example/campusguide/MapsActivity.kt
> +import kotlinx.android.synthetic.main.activity_maps.*
Organize the imports (android studio should have an option to order them)

2020-02-25 21:11 UTC, felixlapierre commented on app/src/main/java/com/example/campusguide/MapsActivity.kt
> +    }
Move this to constants.kt

2020-02-25 21:11 UTC, felixlapierre commented on app/src/main/java/com/example/campusguide/MapsActivity.kt
> +    GoogleApiClient.ConnectionCallbacks, GoogleApiClient.OnConnectionFailedListener {
This feature adds a significant amount of code to the already large MapsActivity, can you extract the functionality into another class?

2020-02-25 21:11 UTC, felixlapierre commented on app/src/main/java/com/example/campusguide/MapsActivity.kt
> +    override fun onLocationChanged(location: Location) {
What does this function do?

2020-02-25 21:11 UTC, felixlapierre commented on app/src/main/java/com/example/campusguide/SwitchCampus.kt
> +            campusName.text = "Loyola Campus"
Move to constants or to string resource

2020-02-26 01:58 UTC, MikeBrichko commented on .idea/codeStyles/Project.xml
> -    <AndroidXmlCodeStyleSettings>
I did not physically change this, I will look into what it means

2020-02-26 01:58 UTC, MikeBrichko commented on app/build.gradle
> +    testImplementation 'junit:junit:4.12'
File will be removed

2020-02-26 01:58 UTC, MikeBrichko commented on app/build.gradle
> -    implementation 'androidx.core:core-ktx:1.0.2'
Features still work, I believe we do not need these dependencies

2020-02-26 01:58 UTC, MikeBrichko commented on app/local.properties
> +sdk.dir=C\:\\Users\\wmike\\AppData\\Local\\Android\\sdk
I removed it, thank you for spotting that

2020-02-26 01:58 UTC, MikeBrichko commented on app/src/main/AndroidManifest.xml
> +        <uses-library android:name="org.apache.http.legacy" android:required="false"/>
The apps behavior does not change if I remove this line, should we remove this line?

2020-02-26 01:58 UTC, MikeBrichko commented on app/src/main/java/com/example/campusguide/MapsActivity.kt
> +import kotlinx.android.synthetic.main.activity_maps.*
It has been done, will be visible in next commit

2020-02-26 01:58 UTC, MikeBrichko commented on app/src/main/java/com/example/campusguide/MapsActivity.kt
> +    GoogleApiClient.ConnectionCallbacks, GoogleApiClient.OnConnectionFailedListener {
I will add it in another class

2020-02-26 01:58 UTC, MikeBrichko commented on app/src/main/java/com/example/campusguide/MapsActivity.kt
> +    }
Sounds good!

2020-02-26 01:58 UTC, MikeBrichko commented on app/src/main/java/com/example/campusguide/MapsActivity.kt
> +    override fun onLocationChanged(location: Location) {
It does nothing, I will remove it

2020-02-26 01:58 UTC, MikeBrichko commented on app/src/main/java/com/example/campusguide/SwitchCampus.kt
> +            campusName.text = "Loyola Campus"
I'll do that!

2020-02-27 04:05 UTC, felixlapierre commented on .idea/codeStyles/Project.xml
> -    <AndroidXmlCodeStyleSettings>
I looked into it and it's just a code style guide thing, not critical

2020-03-01 22:51 UTC, felixlapierre approved these changes

2020-03-01 22:52 UTC, felixlapierre commented on app/src/main/java/com/example/campusguide/MapsActivity.kt
> +    GoogleApiClient.ConnectionCallbacks, GoogleApiClient.OnConnectionFailedListener {
We decided to move the code later

2020-03-01 22:57 UTC, FGRCL approved these changes

2020-03-01 23:17 UTC, felixlapierre requested changes
Fix merge conflict

2020-03-01 23:17 UTC, felixlapierre commented on app/build.gradle
> +<<<<<<< HEAD
You didn't fix this merge conflict. Next time, make sure the build passes before you commit.

2020-03-01 23:42 UTC, felixlapierre approved these changes

2020-03-01 23:42 UTC, merged